config/routes.rb
Rails.application.routes.draw do
  root to: 'application#welcome'

  get 'movies/grouped_ratings', to: 'movies#ratings'

  resources :reviews
  resources :movies do
  resources :reviews, only: [:new, :index]
  end 

  resources :genres
  devise_for :users, path: "users", :controllers => {registrations: 'registrations', :omniauth_callbacks => "callbacks" }
  #devise only handles users



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :movies
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :reviews
  has_many :users, through: :reviews
  belongs_to :genre

  accepts_nested_attributes_for :genre

  validates :name, presence: true
  validates :description, presence: true

  scope :grouped_ratings, -> {left_joins(:reviews).group(:id).order('avg(stars) desc')} #scope

  def self.alphabetical_order #scope
    order(:name)
  end

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :movie
  belongs_to :user

  def self.random_review
    Review.all.sample
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews
  has_many :reviewed_movies, through: :reviews, source: :movie

  has_many :movies #That the user has created

  validates :username, uniqueness: true, presence: true
  validates :email, uniqueness: true, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable,
         omniauth_providers: [:google_oauth2]


  def self.from_omniauth(provider, uid, name, email) 
    where(provider: provider, uid: uid).first_or_create do |user|
      user.email = email
      user.password = Devise.friendly_token[0, 20]
      user.username = name
        # assuming the user model has a name
               # If you are using confirmable and the provider(s) you use validate emails,
               # uncomment the line below to skip the confirmation emails.
               # user.skip_confirmation!
    end
  end
end

app/controllers/application_controller.rb
require 'google/apis/people_v1'
require 'google/api_client/client_secrets.rb'
class ApplicationController < ActionController::Base
  People = Google::Apis::PeopleV1


  
  # def contacts
  #   secrets = Google::APIClient::ClientSecrets.new(
  #     {
  #       "web" =>
  #         {
  #           "access_token" => current_user.token,
  #           "refresh_token" => current_user.refresh_token,
  #           "client_id" => Rails.application.credentials.dig(:google, :google_client_id),
  #           "client_secret" => Rails.application.credentials.dig(:google, :google_secret)
  #         }
  #     }
  #   )
  #   service = People::PeopleServiceService.new
  #   service.authorization = secrets.to_authorization
  #   response = service.list_person_connections(
  #     'people/me',
  #      person_fields: ['names', 'emailAddresses', 'phoneNumbers']
  #   )
  #   render json: response
  # end


  def welcome
  end
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController

  def google_oauth2
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"].provider, request.env["omniauth.auth"].uid, request.env["omniauth.auth"].extra.raw_info.name, request.env["omniauth.auth"].info.email)
    if @user.persisted? #Active Record Method, Returns true if the record is persisted, i.e. it’s not a new record and it was not destroyed, otherwise returns false.
    flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.google_data'] = request.env['omniauth.auth'].uid # Removing extra as it can overflow some session stores/CookieOverflow
      redirect_to new_user_registration_url
    end
  end
end

#DeviseCallBacksTutorial

app/controllers/genres_controller.rb
class GenresController < ApplicationController

  def index
    @genres = Genre.all 
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  #before_action :find_movie, only:[:show, :update, :destroy]
  #Rails API in comments

  def index
    @movies = Movie.all
    #render json: @movies
  end

  def new #Will not need using api
    @movie = Movie.new
    @movie.build_genre #Build/another word for new object
  end

  def create
    @movie = Movie.new(movie_params)
    @movie.user_id = current_user.id
    if @movie.save
      redirect_to movies_path
    else
        @movie.build_genre #Build/another word for new object
      render :new
    end
  end

  def ratings
    @movies = Movie.grouped_ratings #gives access to scope method
  end

  def destroy
    #@movie.destroy
    #render json: @movie
  end

private

  def movie_params
    params.require(:movie).permit(:name, :description, :user_id, :genre_id, genre_attributes: [:name]) #schema
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private
      def sign_up_params
          params.require(:user).permit(:username, :email, :password, :password_confirmation)
      end

      def account_update_params
          params.require(:user).permit(:username, :email, :password, :password_confirmation)
      end
end
#Done within Devise 

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  #before_action :find_review, only:[:show, :update, :destroy]

  def index
    if @movie = Movie.find_by_id(params[:movie_id])
      @reviews = @movie.reviews.all
    else
      @reviews = Review.all
    end
  end

  def new
    if @movie = Movie.find_by_id(params[:movie_id])
       @review = @movie.reviews.build
    else
       @review = Review.new
    end
  end

  def create
    #@review = Review.new(review_params)
    #if @review.save
    #render json: @review
    #else
    #render json: {errors: @review.error.full_messages}
    @review = current_user.reviews.build(review_params) #Stored in private (review_params)
    if @review.save
        redirect_to review_path(@review)
          #render json: @reviews
    else
        render :new
    end
  end

  def show
    @review = Review.find_by_id(params[:id])
      #render json: @review
  end

  def edit #Will not need using api
      @review = Review.find_by_id(params[:id])
  end

  def update
    #if @review.update(review_params)
    #render json: @review
    #else
    #render json: {errors: @review.error.full_messages}
    #end
    @review = Review.find_by_id(params[:id])
    @review.update(review_params)
    redirect_to review_path(@review)
  end

  def destroy
    #@review.destroy
    #render json: @review
  end

  def blank_stars
    5 - stars.to_i
  end

  private
  #def find_review
  #@review = Review.find_by_id(params[:id])
  #end

  def review_params
    params.require(:review).permit(:stars, :title, :content, :movie_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/application/welcome.html.erb
<!-- Header -->
  <div class="w3-container" style="margin-top:80px" id="showcase">
    <h1 class="w3-jumbo"><b>Welcome to Movie Groove!</b></h1>
    <hr style="width:50px;border:5px solid red" class="w3-round">
  </div>


  <div class="w3-container" id="services" style="margin-top:75px">
    <h1 class="w3-xxxlarge w3-text-red"><b><%= Review.random_review.title %></b></h1>
    <hr style="width:50px;border:5px solid red" class="w3-round">
    <p> <%= Review.random_review.content %> </p> 
  </div>


  <!-- Services -->
 <div class="w3-container" id="services" style="margin-top:75px">
   <h1 class="w3-xxxlarge w3-text-red"><b>Services.</b></h1>
   <hr style="width:50px;border:5px solid red" class="w3-round">
   <p>We are movie buffs that love all things movie related!</p>
   <p>Come check out reviews from our dedicated, trustworthy bunch of movie buffs or create your own.
     We have the experience that can handle all genres. Come join in and we will supply the popcorn!</p>
 </div>




 <!-- The Team -->
 <!-- Designers -->
 <div class="w3-container" id="designers" style="margin-top:75px">
   <h1 class="w3-xxxlarge w3-text-red"><b>The Team.</b></h1>
   <hr style="width:50px;border:5px solid red" class="w3-round">

 <div class="w3-row-padding w3-grayscale">
   <div class="w3-col m4 w3-margin-bottom">
     <div class="w3-light-grey">
       <img src="/w3images/team2.jpg" alt="Luke" style="width:100%">
       <div class="w3-container">
         <h3>Luke Skywalker</h3>
         <p class="w3-opacity">CEO & Founder</p>
         <p>Luke Skywalker was a Tatooine farmboy who rose from humble beginnings to become one of the greatest Jedi the galaxy has ever known.</p>
       </div>
     </div>
   </div>
   <div class="w3-col m4 w3-margin-bottom">
     <div class="w3-light-grey">
       <img src="/w3images/team1.jpg" alt="Baby Yoda" style="width:100%">
       <div class="w3-container">
         <h3>Baby Yoda</h3>
         <p class="w3-opacity">In Training</p>
         <p>Baby Yoda is small and 50 years old, but don't let age and size fool you! He is our newest up and coming groover!</p>
       </div>
     </div>
   </div>
   <div class="w3-col m4 w3-margin-bottom">
     <div class="w3-light-grey">
       <img src="/w3images/team3.jpg" alt="Obi Wan" style="width:100%">
       <div class="w3-container">
         <h3>Obi Wan Kenobi</h3>
         <p class="w3-opacity">Critic</p>
         <p>A legendary Jedi Master, Obi-Wan Kenobi He trained Anakin Skywalker, served as a general in the Republic Army during the Clone Wars, and guided Luke Skywalker as a mentor.</p>
       </div>
     </div>
   </div>
 </div>


 <!-- Contact -->
  <div class="w3-container" id="contact" style="margin-top:75px">
    <h1 class="w3-xxxlarge w3-text-red"><b>Contact.</b></h1>
    <hr style="width:50px;border:5px solid red" class="w3-round">
    <p>Do you want to contact us? Fill out the form and our team will be in touch.</p>
    <form action="/action_page.php" target="_blank">
      <div class="w3-section">
        <label>Name</label>
        <input class="w3-input w3-border" type="text" name="Name" required>
      </div>
      <div class="w3-section">
        <label>Email</label>
        <input class="w3-input w3-border" type="text" name="Email" required>
      </div>
      <div class="w3-section">
        <label>Message</label>
        <input class="w3-input w3-border" type="text" name="Message" required>
      </div>
      <button type="submit" class="w3-button w3-block w3-padding-large w3-red w3-margin-bottom">Send Message</button>
    </form>
  </div>

<!-- End page content -->
</div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_nav.html.erb
<!-- Sidebar/menu -->
<nav class="w3-sidebar w3-red w3-collapse w3-top w3-large w3-padding" style="z-index:3;width:300px;font-weight:bold;" id="mySidebar"><br>
  <a href="javascript:void(0)" onclick="w3_close()" class="w3-button w3-hide-large w3-display-topleft" style="width:100%;font-size:22px">Close Menu</a>
  <div class="w3-container">
    <h3 class="w3-padding-64"><b> Get your groove on</h3>
  </div>
  <div class="w3-bar-block">
    <% if !user_signed_in? %>
          <li class="w3-bar-item w3-button w3-hover-white"><%= link_to "Login", new_user_session_path %></li>
          <li class="w3-bar-item w3-button w3-hover-white"><%= link_to "Signup", new_user_registration_path %></li>
          <li class="w3-bar-item w3-button w3-hover-white"><%= link_to "See all reviews", reviews_path %></li>
    <% else %>
          <li class="w3-bar-item w3-button w3-hover-white"><%= link_to "Add a Movie", new_movie_path %></li>
          <li class="w3-bar-item w3-button w3-hover-white"><%= link_to "See all reviews", reviews_path %></li>
          <li class="w3-bar-item w3-button w3-hover-white"><%= link_to "Add a review", new_review_path %></li> 
          <li class="w3-bar-item w3-button w3-hover-white"><%= link_to "Logout", destroy_user_session_path, method: "delete" %></li>
    <% end %>
  </div>
</nav>
<!-- Top menu on small screens -->
<header class="w3-container w3-top w3-hide-large w3-red w3-xlarge w3-padding">
  <a href="javascript:void(0)" class="w3-button w3-red w3-margin-right" onclick="w3_open()">☰</a>
  <span>Movie Groove</span>
</header>

<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieGrooveApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
    body,h1,h2,h3,h4,h5 {font-family: "Poppins", sans-serif}
    body {font-size:16px;}
    .w3-half img{margin-bottom:-6px;margin-top:16px;opacity:0.8;cursor:pointer}
    .w3-half img:hover{opacity:1}
    .checked {
  color: orange;
}
    </style>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
    <%= render 'layouts/nav' %>
    <!-- !PAGE CONTENT! -->
    <div class="w3-main" style="margin-left:340px;margin-right:40px">
    <%= yield %>
    </div>



    <script>
// Script to open and close sidebar
function w3_open() {
  document.getElementById("mySidebar").style.display = "block";
  document.getElementById("myOverlay").style.display = "block";
}

function w3_close() {
  document.getElementById("mySidebar").style.display = "none";
  document.getElementById("myOverlay").style.display = "none";
}

// Modal Image Gallery
function onClick(element) {
  document.getElementById("img01").src = element.src;
  document.getElementById("modal01").style.display = "block";
  var captionText = document.getElementById("caption");
  captionText.innerHTML = element.alt;
}
</script>

  </body>
</html>

app/views/movies/_form.html.erb
<h1> You are grooving! </h1>
<%= render partial: 'layouts/errors', locals:{object: @movie}%>

<%= form_for(@movie) do |f|%>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>



  <p> Select a Genre that already exists: </p>
  <div>
    <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "Pick one" %>

  </div>

  <p> Or create a new Genre: </p>
  <div>
    <%= f.fields_for :genre do |g| %>
      <%= g.label :name %>
      <%= g.text_field :name %>
    <% end %>
  </div>

  <%= f.submit %>
<% end %>

app/views/movies/index.html.erb
<h1> What review would you like to read? </h1>

<%= @movies.each do |m| %>
    <h2> <%= m.name %> </h2>
    <p> <%= m.description %> </p>
<% end %>

app/views/movies/new.html.erb
<%= render partial: 'form' %>

app/views/movies/ratings.html.erb
<h1> Check out these groovy ratings </h1>

<% @movies.each do |m| %>
  <h2><%= m.name %> - <%= m.description %></h2>
  <% m.reviews.each do |r| %>
    <h4><%= r.title %> - <%= r.stars %></h4>
    <p><%= r.content %></p>
  <% end %>
  <%= link_to "Review this movie", new_movie_review_path(m)%>
<% end %>

app/views/reviews/edit.html.erb
<%= form_for(@review) do |f|%>

   <div>
      <%= f.label :movie_id, "Select a Movie" %>
      <%= f.collection_select :movie_id, Movie.all, :id, :name, include_blank: true %>
  </div>


  <div>
    <%= f.label :stars %>
    <%= f.number_field :stars, min:1, max:5 %>
  </div>

  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>




  <%= f.submit %>

  <% end %>

app/views/reviews/index.html.erb
<% if @movie %>
    <h1> View all the reviews for <%= @movie.name %>!</h1>
<% else %>
    <h1> View all the groovy reviews </h1>
<% end %>



<% @reviews.each do |r| %>
    <h2> <%= r.movie.name %> </h2>
    <h2> <%= r.title %> - <%= r.stars %> </h2>
    <p> <%= r.content %> </p>
    <%= link_to "Edit your review", edit_review_path(r.id) %>
<% end %>

app/views/reviews/new.html.erb
<%= render partial: 'layouts/errors', locals:{object: @review}%>
<% if @movie %>
    <h1> Let's write a groovy review for <%= @movie.genre.name %> <%= @movie.name %>!</h1>
<% else %>
    <h1> Add a groovy Review! </h1>
<% end %>


<%= form_for(@review) do |f|%>
<% if params[:movie_id] %>
   <%= f.hidden_field :movie_id %>
<% else %>
   <div>
      <%= f.label :movie_id, "Select a Movie" %>
      <%= f.collection_select :movie_id, Movie.all, :id, :name, include_blank: true %>
  </div>
  <% end %>

  <div>
    <%= f.label :stars %>
    <%= f.number_field :stars, min:1, max:5 %>
  </div>

  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <%= f.submit %>

  <% end %>

app/views/reviews/show.html.erb
<h1> Here is your groovy review </h1>


<h2><%= @review.title %></h2>

<h3><%= @review.stars %></h3>

<p><%= @review.content %></p>


<%= link_to "Edit your review", edit_review_path(@review) %>